FROM node:24.15.0-alpine3.23

WORKDIR /usr/src/app

RUN corepack enable pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm exec prisma generate

EXPOSE $SERVER_PORT

CMD ["pnpm", "run", "start:dev"]
