on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - ${{ vars.DB_PORT }}:5432
        env:
          POSTGRES_DB: ${{ vars.DB_NAME }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      API_HOST: ${{ vars.API_HOST }}
      API_PORT: ${{ vars.API_PORT }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SCHEMA: ${{ vars.DB_SCHEMA }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY: ${{ vars.JWT_PUBLIC_KEY }}
      HASH_SALT: ${{ secrets.HASH_SALT }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.26.1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24.15.0
        cache: pnpm

    - name: Install dependencies
      run: |
        pnpm install --frozen-lockfile

    - name: Run build
      run: |
        pnpm build

    - name: Set up the database
      run: |
        pnpm exec prisma migrate deploy

    - name: Test Coverage
      run: |
        pnpm test:ci

    - name: Coveralls
      uses: coverallsapp/github-action@v2
